markdown: kramdown 
permalink: /:year/:month/:title 
title: 读书卡片
url: https://www.weihaisheng.com
subscribe: http://kapian.weihaisheng.com/feed
exclude: [ README.md, newpost.rb ]
domain: kapian.weihaisheng.com
author: bjt
email: admin@weihaisheng.com
safe: true
theme: jekyll-theme-cayman
