markdown: kramdown
permalink: /:year/:month/:title 
title: 打卡备忘录
url: https://daka.weihaisheng.com/
subscribe: https://daka.weihaisheng.com/feed
exclude: [ README.md, newpost.rb ]
domain: https://daka.weihaisheng.com/
author: weihaisheng
email: admin@weihaisheng.com
twitterID: weihaisheng
disqusShortname: weihaisheng
safe: true
