markdown: kramdown
permalink: /:title.html
title: 方寸之地
tagline:点滴汇小流，方寸见天地
url: https://www.fangcunzhidi.com/
subscribe: https://www.fangcunzhidi.com/feed
exclude: [ README.md, newpost.rb ]
domain: https://www.fangcunzhidi.com/
author: 立言力行
email: tier_523@163.com
disqusShortname: louisChen
safe: true

theme: jekyll-theme-midnight
