markdown: kramdown
permalink: /:title.html
title: 每日读写记
url: https://www.duxieji.com/
subscribe: https://www.duxieji.com/feed
exclude: [ README.md, newpost.rb ]
domain: https://www.duxieji.com/
author: weihaisheng
email: admin@weihaisheng.com
twitterID: weihaisheng
disqusShortname: weihaisheng
safe: true

theme: jekyll-theme-midnight
